name: Run testing

on:
  push:

jobs:
  testing:
    name: Unit test
    runs-on: ubuntu-latest
    container: golang:1.17-alpine3.14
    steps:
      - uses: actions/checkout@v2
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.16
      - name: Running unit test
        run: |
          go mod tidy
          go test ./.. -v -cover